### ISSUE TITLE
Failed to add custom schema properties, aborting script

### ISSUE THREAD

**Issue by jeroenbe** [okta/stormpath-migration#50]
Hi, I exported my SP data, decrypted the export and installed the import-stormpath tool. Using this tool with every required variable yielded following error: `Failed to add custom schema properties, aborting script`. stack:
```bash
StatusCodeError: 404 - "<!DOCTYPE html>\n<html class=\"no-js\" lang=\"en\" dir=\"ltr\">\n<head>\n  <script>\n    var isProduction = window.location.hostname === 'developer.okta.com';\n    if (isProduction) {\n      // TypeKit\n      (function(d) {\n        var config = {\n          kitId: 'jff5neq',\n          scriptTimeout: 3000,\n          async: true\n        },\n        h=d.documentElement,t=setTimeout(function(){h.className=h.className.replace(/\\bwf-loading\\b/g,\"\")+\" wf-inactive\";},config.scriptTimeout),tk=d.createElement(\"script\"),f=false,s=d.getElementsByTagName(\"script\")[0],a;h.className+=\" wf-loading\";tk.src='https://use.typekit.net/'+config.kitId+'.js';tk.async=true;tk.onload=tk.onreadystatechange=function(){a=this.readyState;if(f||a&&a!=\"complete\"&&a!=\"loaded\")return;f=true;clearTimeout(t);try{Typekit.load(config)}catch(e){}};s.parentNode.insertBefore(tk,s)\n      })(document);\n\n      // Google analytics\n      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){\n              (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),\n              m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)\n      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');\n      ga('create', 'UA-15777010-3', 'auto');\n      ga('send', 'pageview');\n    }\n\t</script>\n  <meta charset=\"utf-8\">\n  <meta http-equiv=\"x-ua-compatible\" content=\"IE=edge,chrome=1\">\n  <meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\n  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n \t\n \t\t<meta name=\"robots\" content=\"noindex,nofollow\">\n \t\n  <link type=\"text/css\" rel=\"stylesheet\" href=\"/assets/animate-ec43d72c3ed45e08a460b8a2966d8dba6006aebfa0530935c3973fa493a8771f.css\">\n  <link type=\"text/css\" rel=\"stylesheet\" href=\"/assets/okta-fe3337502d4360bcb36814ced8dd4f88ec4c9e7d7a0be6fa2995c3524314aa7d.css\">\n  \n  \n  <link rel=\"shortcut icon\" type=\"image/vnd.microsoft.icon\" href=\"/favicon.ico\">\n  <title>Page Not Found | Okta Developer</title>\n  <meta name=\"description\" content=\"Secure, scalable, and highly available authentication and user management for any app.\n\">\n  <link rel=\"canonical\" href=\"https://developer.okta.com/404.html\">\n  <link rel=\"alternate\" type=\"application/rss+xml\" title=\"Okta Developer\" href=\"https://developer.okta.com/feed.xml\"><!-- GA -->\n</head>\n\n<body>\n  <div class=\"Page page-not-found\">\n    <!-- START Header -->\n    <header id=\"header\">\n      <div class=\"Wrap\">\n        <h1 class=\"logo\"><a href=\"/\">Okta</a></h1><!-- START Primary Nav -->\n        <nav>\n          <div id=\"top-nav\">\n            <a href=\"#\" id=\"mobile-close\" class=\"mobile-toggle\">\n              <span></span>\n              <span></span>\n            </a>\n            <a class=\"Button--green\" href=\"https://developer.okta.com/signup/\" id=\"top-nav-cta\">Get Started</a>\n            <a class=\"SearchIcon\" href=\"#\"></a>\n            <ul>\n              <li>\n                <a href=\"/product/\">Product</a>\n              </li>\n              <li>\n                <a href=\"/documentation/\">Documentation</a>\n              </li>\n              <li>\n                <a href=\"/code/\">Code</a>\n              </li>\n              <li class=\"has-dropdown\">\n                <a href=\"#\">Support</a>\n                <div class=\"dropdown-window\">\n                  <p class=\"devforum\">Post your question on <a href=\"https://devforum.okta.com/\" title=\"Okta Developer Forums\" target=\"_blank\">Okta Developer Forums</a></p>\n                  <p class=\"email\">Email us:<br>\n                  <a href=\"mailto:developers@okta.com\">developers@okta.com</a></p>\n                  <p class=\"tel\">Call us:<br>\n                  <a href=\"tel:18887227871\">1 (888) 722-7871</a></p>\n                </div>\n              </li>\n            </ul>\n            <form id=\"form_search\" method=\"get\" action=\"/search/\" name=\"form_search\">\n              <input type=\"text\" name=\"q\" id=\"q\" autocomplete=\"off\">\n            </form>\n          </div>\n          <div id=\"mobile-nav\">\n            <a id=\"mobile-search\" href=\"/search/\"><span class=\"icon-search-light\"></span></a>\n            <a id=\"mobile-open\" class=\"mobile-toggle\" href=\"#top-nav\">\n              <span></span>\n              <span></span>\n              <span></span>\n            </a>\n          </div>\n        </nav><!-- END Primary Nav -->\n      </div>\n    </header><!-- Google Tag Manager -->\n    <noscript><iframe src=\"//www.googletagmanager.com/ns.html?id=GTM-TJ45R6\" height=\"0\" width=\"0\" style=\"display:none;visibility:hidden\"></iframe></noscript>\n    <script>\n      if (isProduction) {\n        (function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':\n        new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],\n        j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=\n        '//www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);\n        })(window,document,'script','dataLayer','GTM-TJ45R6');\n      }\n    </script> <!-- End Google Tag Manager -->\n     <!-- END Header -->\n        <style>\n      h3 {\n        color: #5d5d5d !important;\n      }\n    </style>\n    <!-- START Page Center w/Sub Nav & Content -->\n    <section class=\"PageContent\">\n      <!-- START Page Content -->\n      <div class=\"PageContent-main\">\n      <section>\n\t<h3>404 Page Not Found</h3>\n\n\t<p>The web page or file you were trying to reach cannot be found. It may have been moved to a different location or removed because the information it contained is no longer valid.</p>\n\n\t<p>Common errors that can result in broken links include:</p>\n\n\t<ul>\n\t\t<li>Truncated URLs.<br/>Some email applications may break a URL due to line breaks. You may need to cut and paste a URL from your email application into your browser's location field.</li>\n\t\t<li>Case Sensitivity.<br/>URL's are case sensitive. \"File.html\" and \"file.html\" are not considered the same file by the server. Please verify that the URL is entered correctly as printed.</li>\n\t</ul>\n\n\t<p>Please <a href=\"mailto:developers@okta.com\">email</a> your feedback/comments.</p>\n\n</section>\n\n      </div>\n      <!-- END Page Content -->\n    </section>\n    <!-- END Page Center w/Sub Nav & Content -->\n\n    <!-- START Footer -->\n    <footer class=\"footer\">\n      <div class=\"Wrap\">\n        <ul>\n          <li>\n            <a href=\"https://www.okta.com\" target=\"_blank\">Okta.com</a>\n          </li>\n          <li>\n            <a href=\"/blog/\">Blog</a>\n          </li>\n          <li>\n            <a href=\"/docs/platform-release-notes/platform-release-notes.html\">Platform Release Notes</a>\n          </li>\n          <li>\n            <a href=\"/terms/\">Terms & Conditions</a>\n          </li>\n          <li>\n            <a href=\"/3rd_party_notices/\">3rd Party Notices</a>\n          </li>\n          <li>\n            <a href=\"/privacy/\">Privacy Policy</a>\n          </li>\n          <li>\n            <a href=\"/contact/\">Contact Sales</a>\n          </li>\n          <li>\n            <a href=\"mailto:developers@okta.com\">Contact Support</a>\n          </li>\n        </ul>\n        <ul>\n          <li>\n            <a class=\"icon\" href=\"http://github.com/oktadeveloper\" target=\"_blank\"><i class=\"fa fa-github\"></i></a>\n          </li>\n          <li>\n            <a class=\"icon\" href=\"http://twitter.com/okta\" target=\"_blank\"><i class=\"fa fa-twitter\"></i></a>\n          </li>\n          <li>\n            <a class=\"icon\" href=\"https://devforum.okta.com/\" title=\"Okta Developer Forums\" target=\"_blank\"><i class=\"fa fa-comments\"></i></a>\n          </li>\n          <li>\n            <a class=\"icon\" href=\"http://feeds.feedburner.com/OktaBlog\" target=\"_blank\"><i class=\"fa fa-rss\"></i></a>\n          </li><!-- <li><a class=\"icon\" href=\"http://community.okta.com\" target=\"_blank\"><i class=\"fa fa-comments\"></i></a></li> -->\n        </ul>\n      </div>\n    </footer>\n    <script type=\"text/javascript\" src=\"/assets/master-d164e3cb90ad42ea74c141546269db0efdbc2259b7d44b7f52babb60097099a8.js\"></script>\n    \n    \n    \n    \n    <!-- Remarketing tag -->\n    <script type=\"text/javascript\">\n        /* <![CDATA[ */\n        var google_conversion_id = 1006913831;\n        var google_custom_params = window.google_tag_params;\n        var google_remarketing_only = true;\n        /* ]]> */\n    </script>\n    <div style=\"display:none;\">\n      <script type=\"text/javascript\" src=\"//www.googleadservices.com/pagead/conversion.js\"></script>\n    </div>\n    <noscript>\n      <div style=\"display:inline;\">\n        <img height=\"1\" width=\"1\" style=\"border-style:none;\" alt=\"\" src=\"//googleads.g.doubleclick.net/pagead/viewthroughconversion/1006913831/?value=0&amp;guid=ON&amp;script=0\">\n      </div>\n    </noscript>\n    <!-- End Remarketing tag -->\n    <!-- Crazy Egg Tracking -->\n    <script type=\"text/javascript\">\n    setTimeout(function(){var a=document.createElement(\"script\");\n    var b=document.getElementsByTagName(\"script\")[0];\n    a.src=document.location.protocol+\"//script.crazyegg.com/pages/scripts/0021/9333.js?\"+Math.floor(new Date().getTime()/3600000);\n    a.async=true;a.type=\"text/javascript\";b.parentNode.insertBefore(a,b)}, 1);\n    </script>\n    <!-- End Crazy Egg Tracking -->\n\n     <!-- END Footer -->\n  </div>\n</body>\n</html>\n"
          at new StatusCodeError (/usr/local/lib/node_modules/@okta/stormpath-migration/node_modules/request-promise-core/lib/errors.js:32:15)
          at Request.plumbing.callback (/usr/local/lib/node_modules/@okta/stormpath-migration/node_modules/request-promise-core/lib/plumbing.js:104:33)
          at Request.RP$callback [as _callback] (/usr/local/lib/node_modules/@okta/stormpath-migration/node_modules/request-promise-core/lib/plumbing.js:46:31)
          at Request.self.callback (/usr/local/lib/node_modules/@okta/stormpath-migration/node_modules/request/request.js:188:22)
          at emitTwo (events.js:125:13)
          at Request.emit (events.js:213:7)
          at Request.<anonymous> (/usr/local/lib/node_modules/@okta/stormpath-migration/node_modules/request/request.js:1171:10)
          at emitOne (events.js:115:13)
          at Request.emit (events.js:210:7)
          at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/@okta/stormpath-migration/node_modules/request/request.js:1091:12)
          at Object.onceWrapper (events.js:314:30)
          at emitNone (events.js:110:20)
          at IncomingMessage.emit (events.js:207:7)
          at endReadableNT (_stream_readable.js:1045:12)
          at _combinedTickCallback (internal/process/next_tick.js:102:11)
          at process._tickCallback (internal/process/next_tick.js:161:9)
```

Which indicates a 404. Please note, I have not created any applications in Okta yet (as the migration guide did not stated I should).

Thanks!

**Comment by mdeggies** [comment]
Hey @jeroenbe, thanks for sending this over. Can you reach out to developers@okta.com with your stacktrace? I can help you there.
